number1=float(input("what is your first number?"))
number2=float(input("what is your second number?"))
number3=float(input("what is your third number?"))
numbers=((number1+number2+number3)/2)
print(f"{number1}+{number2}+{number3}/2 is...{numbers}")